#!/usr/bin/env ruby
# Applies plugin severity/name labels from a CSV lookup file to postprocessor files.
#
# Usage:
#   ruby tools/apply_plugin_labels.rb tools/plugin_lookup.csv
#
# The CSV should have columns: plugin_id,severity,name
# Generated by tools/lookup_plugin_ids.rb
#
# Updates lines to format: 12345, #HIGH, Plugin Name Here
# Handles bare IDs, old-style comments, and existing names without severity.

require 'csv'

if ARGV.empty?
  puts "Usage: ruby tools/apply_plugin_labels.rb <lookup.csv>"
  exit 1
end

csv_file = ARGV[0]

unless File.exist?(csv_file)
  puts "File not found: #{csv_file}"
  exit 1
end

# Load lookup data
lookup = {}
CSV.foreach(csv_file, headers: true) do |row|
  id = row["plugin_id"].to_i
  severity = row["severity"]
  name = row["name"]

  next if severity == "UNKNOWN" || name.nil? || name.empty?

  lookup[id] = { severity: severity, name: name }
end

puts "Loaded #{lookup.size} plugin labels"

# Process each postprocessor file
updated_files = 0
updated_lines = 0

Dir.glob("lib/risu/parsers/nessus/postprocess/*.rb").sort.each do |file|
  lines = File.readlines(file)
  changed = false

  lines.each_with_index do |line, idx|
    # Match any plugin ID line that doesn't already have the correct format
    next unless line =~ /^(\s*)(\d+),/
    indent = $1
    plugin_id = $2.to_i
    next if plugin_id == 0

    # Skip if already has severity format
    next if line =~ /#(CRITICAL|HIGH|MEDIUM|LOW|INFO),/

    if lookup.key?(plugin_id)
      info = lookup[plugin_id]
      new_line = "#{indent}#{plugin_id}, ##{info[:severity]}, #{info[:name]}\n"
      lines[idx] = new_line
      changed = true
      updated_lines += 1
    end
  end

  if changed
    File.write(file, lines.join)
    updated_files += 1
    puts "Updated: #{File.basename(file)}"
  end
end

puts "---"
puts "Updated #{updated_lines} lines across #{updated_files} files"
